deps: update Jekyll
This updates Jekyll to include
https://github.com/jekyll/jekyll/pull/9392.

Without this update, `make` produces

To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
jekyll 4.2.0 | Error:  undefined method `[]' for nil
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
        from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.0/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
        from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.0/lib/jekyll/configuration.rb:143:in `config_files'
        from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.0/lib/jekyll.rb:118:in `configuration'
        from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:44:in `configuration_from_options'
        from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/local/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/local/lib/ruby/gems/3.3.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.3.0/bin/jekyll:25:in `load'
        from /usr/local/lib/ruby/gems/3.3.0/bin/jekyll:25:in `<top (required)>'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/Cellar/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
        from /usr/local/opt/ruby/bin/bundle:25:in `load'
        from /usr/local/opt/ruby/bin/bundle:25:in `<main>'

Googling suggested that downgrading ruby would work, but Jekyll release
notes (and a hint from https://github.com/apache/arrow-site/pull/451)
suggested the real fix: upgrade Jekyll.

The new warning about the csv module is waiting on a backport release
from Jekyll.